### ISSUE TITLE
Deploying the encoder service

### ISSUE THREAD

**Issue by geohacker** [developmentseed/segment-anything-services#9]
Had a quick chat with @ingalls and @batpad. We'll use a basic ECS cluster with 2 autoscaling groups:
* 1 for CPU that's always-on 
* another one that's GPU backed but by request
* For the first pass we'll have a manual process to increase the min size of the autoscaling group
* Later this can be managed via potentially a simple API gateway endpoint that modifies the min size on the cluster

@ingalls — @rbavery has done pretty much all the work in terms of dockerizing these in this repo. [gpu](https://github.com/developmentseed/segment-anything-geo/blob/main/Dockerfile) and [cpu](https://github.com/developmentseed/segment-anything-geo/blob/main/Dockerfile-cpu). So you should be able to pretty much take that and setup ECS.

I think we could combine this to one image if you need for simplicity. @rbavery would that be ok or are there other considerations? 

cc @srmsoumya

**Comment by rbavery** [comment]
Talked with @geohacker but reiterating here, I separated the GPU encoder service thinking that would be run in an on-demand fashion to keep cost down. Whenever new imagery becomes available, we'd spin up the GPU encoder and then spin it down once we have the embeddings.

The CPU decoder would get used more frequently and consistently on top of the embeddings that were generated, so I was thinking it should be it's separate service that is always running in the backend for something like PEARL.

**Comment by rbavery** [comment]
This is deployed, closing!
